apiVersion: v1  
kind: Namespace
metadata:
  name: webapp-namespace
---

apiVersion: v1
kind: Service 
metadata:
  name: database  
  namespace: webapp-namespace 
spec:
  selector:
    app: database
  ports:
    - protocol: TCP
      port: 3306  
      targetPort: 3306 
---

apiVersion: v1 
kind: PersistentVolumeClaim  
metadata:
  name: database-pvc  
  namespace: webapp-namespace  
spec:
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 1Gi 

---

apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: database 
  namespace: webapp-namespace 
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: database 
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database 
          image: mysql:latest 
          env:
            - name: MYSQL_ROOT_PASSWORD  
              value: "your_root_password" 
          ports:
            - containerPort: 3306  
          volumeMounts:
            - name: database-storage  
              mountPath: /var/lib/mysql 
      volumes:
        - name: database-storage 
          persistentVolumeClaim:
            claimName: database-pvc 

---

apiVersion: v1 
kind: Service 
metadata:
  name: webapp  
  namespace: webapp-namespace  
spec:
  selector:
    app: webapp 
  ports:
    - protocol: TCP  
      port: 80  
      targetPort: 80 
  type: ClusterIP

---

apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: webapp  
  namespace: webapp-namespace  
spec:
  replicas: 3  
  selector:
    matchLabels:
      app: webapp  
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp  
          image: 192.168.59.250:5000/app:BuildNumber 
          ports:
            - containerPort: 80  
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "cp -r /usr/src/app/. /var/www/html"]
          volumeMounts:
            - name: shared-data
              mountPath: /var/www/html
        - name: php
          image: php:8.2-fpm
          ports:
              - containerPort: 9000
          volumeMounts:
            - name: shared-data
              mountPath: /var/www/html
          env:
            - name: DB_HOST  # Переменная окружения для хоста базы данных
              value: database  # Значение переменной окружения - имя сервиса базы данных
            - name: DB_PORT  # Переменная окружения для порта базы данных
              value: "3306"  # Значение переменной окружения - порт базы данных
            - name: DB_USER  # Переменная окружения для пользователя базы данных
              value: "root"  # Значение переменной окружения - ваш пользователь
            - name: DB_PASSWORD  # Переменная окружения для пароля базы данных
              value: "123@Qwerty"  # Значение переменной окружения - ваш пароль
            - name: DB_NAME  # Переменная окружения для названия базы данных
              value: "k8sTEST"  # Значение переменной окружения - название вашей базы данных
      volumes:
        - name: shared-data # Имя тома
          emptyDir: {}

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp-ingress
  namespace: webapp-namespace
spec:
  rules:
  - host: trevico.navbahorholding.uz
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: webapp
            port:
              number: 80
