name: Curl при push

on:
  push:
    branches:
      - '**'

jobs:
  curl_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout кода
      uses: actions/checkout@v2

    - name: Выполнить команду curl
      run: curl -X POST http://81.95.237.202:8080/job/Grovy_Pipe_Line/build?token=k8s
